#!/bin/sh

ghc -package-confdist/package.conf.inplace \
-idist/build/autogen \
-isrc \
-optP-include -optPdist/build/autogen/cabal_macros.h \
-XNoImplicitPrelude \
-XPackageImports \
-XCPP \
-XOverloadedStrings \
-XRecordWildCards \
-XScopedTypeVariables \
-XFlexibleContexts \
-XDeriveDataTypeable \
-XBangPatterns \
-XNoMonomorphismRestriction \
-XTypeSynonymInstances \
-XFlexibleInstances \
-XFlexibleContexts \
-XKindSignatures \
-XScopedTypeVariables \
-XGADTs \
-XTypeFamilies \
-XMultiParamTypeClasses \
-XFunctionalDependencies \
-XQuasiQuotes \
-XTemplateHaskell \
-XBangPatterns \
-XMagicHash \
-XConstraintKinds \
-Wall \
-outputdir=/tmp/_ghctmp \
$@
