#!/bin/sh

ghc -outputdir=/tmp/_ghctmp -optP-include -optPdist/build/autogen/cabal_macros.h -idist/build/autogen -XNoImplicitPrelude -XCPP \
-XOverloadedStrings -XRecordWildCards -XScopedTypeVariables -XFlexibleContexts -XDeriveDataTypeable -XBangPatterns \
-Wall $@
