{-# OPTIONS_GHC -fno-warn-orphans #-}
module
#ifdef COMBINED_CHECK
    GtkMain
#else
    Main
#endif
    (main) where
import Import hiding (on, mod)

import Paths_blast_it_with_piss

import BlastItWithPiss.Board

import GtkBlast.Directory
import GtkBlast.Log
import GtkBlast.Conf
import GtkBlast.EnvParts (createWidgetsAndFillEnv)
import GtkBlast.Mainloop (setMainLoop)
import GtkBlast.Types
import GtkBlast.ROW_ROW_FIGHT_THE_POWER

import Graphics.UI.Gtk hiding (get)

import Data.Version

import System.Environment (getArgs)
import System.Exit

import System.FilePath

#ifdef BINDIST
import System.Directory (setCurrentDirectory)
import System.Environment.Executable (splitExecutablePath)
#endif

import Network (withSocketsDo)

import GHC.Conc

-- TODO new thread, with Manual in OP post
--  (how to check proxies, how to wipe and spam, google 'private proxy' etc)
--  captcha is saved between wipes, but not yet between sessions
--  board settings are not saved
--  "в запасе" means additional captcha, you need numproxys + limit to start wipe
--  at all costs, use linux version

--    -> allowedModes, don't parse page when the only allowed mode is CreateNew
--    -> http://developer.github.com/v3/repos/releases/

-- MOST REQUESTED —
--  presolve captcha
--    -> save and reuse captcha between sessions and zasiralka/smyvalka/checker
--    -> return captchas that were never used (e.g. agent killed in before startwipe signal)
--    -> do not solve outdated captcha keys
--  immutable agents — instead of agents re-reading mu/sh/pr-settings all the
--      time serialize agent state and restart agents on change
--  remove Наебнулось
--    -> deal with cloudflare everywhere
--    -> deal with httpExceptions/convert-to-Outcomes everywhere
--    -> wrap all reqs in 'try', deal with all exceptions immediately.
--    -> deal with captcha 403/503
--  zasiralka performance (page and thread cache)
--    -> basically, limit proxy I/O through page cache
--  zasiralka save banned proxies
--  smyvalka/checker gui captcha
--  proxy authentication (basicauth)
--  freeform board-names
--  testing: replay logs
--     -> the code is ridiculuously sloppy. It basically doesn't do what you'd
--        think it does, and there are no tests to check it.
--  detect ban on all boards, and blacklist proxies accordingly
--  we basically need a rewrite of zasiralka. GUI is horribly entagled with logic.
-- > Можешь топилку отдельных тредов запилить?
-- > То есть, чтобы она бампала все треды, кроме отмеченных, и потом создавала несколько тредов.

-- URGENT Ошибка: в вашем сообщении много ссылок на чужие посты
-- URGENT Отвалилось цитирование, оно >в одну строчку
-- 2ch.tf

-- URGENT MAKE_PRINCIPLED change/parse field names (captcha_value_id_06) at runtime
-- URGENT stop posting pasta after it's labeled as spam.
-- URGENT Interactively edit pasta after it's labeled as spam in smyvalka and zasiralka.
--      Requires smyvalka-GUI/merger.
-- URGENT check wordfilter separately before starting wipe

-- URGENT решать капчу отдельно, сохранять для использования в аппликациях
-- FIXME Капча почему-то привязана к проксям, но ведь это общий пул.
-- URGENT Save unused captchas for later use
-- URGENT Save all captchas, in a db/folder whether generated by zasiralka/smyvalka/proxychecker
-- URGENT all-software: Preserve captcha answers after shutdown
-- URGENT Checker resume after shutdown.

-- MUSTHAVE Include checking facilities (write failing/working proxies+timing)
--          in every piece in software suite
-- URGENT записывать все прокси с которых удалось запостить в файл

-- URGENT Reclaim proxies after failure/Don't discard. Write failures.
--      Таймаут? Подождать 30 секунд после фейла и попробовать ещё?
--      Увеличивать таймаут при повторных фейлах?

-- URGENT Reduce copypasta between smyvalka & checker or merge

-- URGENT table-view-log & filter (Error, Warning, Info, Debug, All)
-- URGENT categorize log messages to reduce clutter, switch to table to add speed (keera)
-- URGENT write outcomes in a table to the right
-- URGENT write log to a table. See
--  https://github.com/keera-studios/keera-hails/blob/master/src/Hails/Graphics/UI/Gtk/Simplify/Logger.hs
--  or geany Compiler tab
-- URGENT better error message when no threads.
-- URGENT post parsed page info to the gui
-- TODO GTK keyboard completion in board list (list view / table / ad-hoc)

-- GOAL merge gtkblast, smyvalka and proxychecker

-- BUG Notify.closeWatcher in GtkUtils kills app under wine?

-- URGENT ввод капчи руками в смывалке и чекере
-- URGENT Лимит TVar с количеством соединений с мочаном, check (< limit): Blast.post
--      Проблема: Нету никакой "честности", прокси могут задохнуться
--      Pool? Queue?

-- TODO Makaba support, if href wakaba w3x then wakaba else makaba, makaba checker

-- URGENT absence of DNS caching creates real problems https://github.com/exbb2/BlastItWithPiss/issues/3
--  We can implement kludgy DNS caching right now, without bothering http-conduit,
--  by simply resolving ssachHost and antigateHost at initialization time.

-- URGENT s/mmode/msagemode
-- URGENT remove wipeStarted

-- TODO DETECT CLOUDFLARE DURING POST
-- URGENT Обход клаудфлера при постинге & клаудфлер в смывалке

-- URGENT
--      CaptchaAnswerWithReport type, CaptchaSolver class
--      ,Generalize BlastItWithPiss.hs to allow it to be used in checker and smyvalka
--      (return post time stamp, instead of sleeping, to allow for a thread pool?)
-- URGENT auto-reportbad, see kludges in checkproxymain

-- URGENT Thread pool (schedule posting / network connections, don't run everything at once)
-- URGENT WeakRef ThreadId
-- URGENT separate read-only "Settings" TVars and internal shared state

-- URGENT — rework outcome hierarchy so that connection errors are different
--      from posting errors, handle specific connection errors(cloudflare) everywhere)

-- URGENT smyvalka: write Log
-- URGENT Avoid reopening log handle
-- URGENT smyvalka: use async
-- URGENT Use FastLogger for date caching

-- URGENT Presolve & migrate captcha (structure captcha solving as a (?term)resource pool/conduit)
-- URGENT observer threads instead of regens

-- URGENT smyvalka show captchas currently in solving

-- TODO показывать количество проксей, а не только воркеров

-- URGENT Glade-3 destroys tooltips on cut/paste. Move setting tooltips to code.

-- URGENT use image when longposting

-- https://github.com/blog/1302-goodbye-uploads
--  dropbox, git-annex, BinTray?
--  bitbucket has Downloads section, we can setup a mirror there.
--  google-code and sourceforge also have Downloads sections


-- == PERFORMANCE ==
-- URGENT Don't reparse threads for every worker.

-- TODO We still can't set higher priority for thread with GUI, (perhaps we could through OS API...)
--      So it'll lag anyway, unless we move workers to different process.
-- TODO System.Random is slow, and might cause some lag on escaping. marsenne-random, mws-random?
-- CLARIFY Does Text leaks on drop? (seems from the source that data before the substring is not GC'd, CLARIFY)
-- CLARIFY we force [Tag Text] completely in blastCloudflare,
--         might not be a problem, since we also parse whole page when deciding mode
--         Does it? Only when status code is 403/404.

-- TODO http-conduit:
--  DNS caching
--  Unify proxy types / Define proxy chains
--  Cookie filter / map, cookie helpers

-- FIXME Is there a memory/resource leak in void $ http (parseUrl "http://example.com")?
--  Yes, There is, see https://github.com/snoyberg/http-conduit/issues/97#issuecomment-12858211

-- == 2.0 RELEASE ==

-- FIXME EnvPart internal state shouldn't really lie around in global env?

-- URGENT FUCKUP To add a new option you need to edit at least 3 files.

-- URGENT synchronize/associate pastas with images/videos
-- TODO shuffleM in pastagen is probably ungodly slow

-- URGENT Some lag in the GUI MIGHT be caused by unevaluated thunks in stm stuff.

-- URGENT Move escaping to pastagen
-- URGENT upload images via conduit source

-- URGENT капча на несколько постов вперед.
-- URGENT in GUI prioritize show thread captcha before cloud captcha
-- URGENT repeat on 503, database error, once on http -- already in PostRejected?

-- URGENT Rid of postGUIAsync in pasta/video/images initialization

-- URGENT показывать причину последнего бана когда все забанены
-- URGENT Записывать конфиг сразу, а не только при закрытии.

-- URGENT Настройка темы, поле имя/трипкод
-- URGENT Разделить ui цитату номера поста и цитату содержимого
-- URGENT настройки тредов: вставлять ссылку на тред, не только номер
-- URGENT blastitwithpiss.github.io
-- TODO Manual.md
-- TODO Stable download links using github pages

-- URGENT Вайпать несколько тредов
-- TODO Настройка стратегии

-- TODO AdaptiveIn is a property of board+proxy not of a single agent
-- TODO ugliest things: regenerations, "old" vars in disableable envparts.

-- TODO Постинг в /o/

-- URGENT
--  Синхронизация юнитов, кэширование страниц(не только нулевой) между проксями
--  на одной борде. Записывать какие треды бампнули с штампом чтобы не бампать
--  дважды. Записывать какие треды создали с ноко, чтобы бампать вайп;
--  BumpUnpopular → BumpWipe, otherwise BumpOld. Перезагрузка некэшированных
--  страниц.
--  + Слежение за тредом, автобамп
-- URGENT parse less often if on a slow board
-- URGENT Rename EnvPart → Widget
-- URGNET blastCloudflare → withCloudflare
-- URGENT ControlCenter type/class which controls wipe units, WipeUnit type.
-- URGENT Remove "{" ++ "}"

-- TODO background mode

-- URGENT MANUAL + corner cases (403, wordfilter, etc.) + use cases (засирание треда, вайп борды, смыв, закос под ручной вайп, автобамп)
-- URGENT Five'o'Three BlastItWithPiss workaround
-- URGENT Поставить запросы на постинг в очередь(avoid wakaba.pl 503)
-- URGENT Better error messages (no parse, 403, etc.)
-- URGENT GHC under Wine HaskellWiki

--Smyvalka
-- FIXME Капча почему-то привязана к проксям, но ведь это общий пул.

--BlastItWithPiss lib:
-- TODO Безжалостное уродование текста (замена на цифры, leet, вставка пробелов/минусов)
-- TODO avoid parsing page when only creating threads / when it's time to
--      create a thread and createthread == always
-- TODO avoid rolling a dice when createthread == always
-- URGENT >Что за пиздец с «этот файл уже загружен»? Неужели трудно по умолчанию менять пару байт в картинке перед отправкой?
--      УМВР вроде.
--      Добавлять мусор ещё и в начале?
-- TODO Не расходовать капчу зря
-- TODO avoid 403 ban
-- TODO небампание (только сажа) определенных тредов (планета) (чёрный список)
-- TODO Merge Blast and BlastLog, expose BlastLog. Merge tpastagen and timagegen
--      into tpostdatagen. debuglog/normallog
-- TODO show offending message in SameMessage and others
-- TODO Abstract out (hierarchical[?]) config management in BlastItWithPiss
-- TODO Перепостинг из других досок
-- TODO оптимизировать ещё (прекратить пложение ОС-тредов? fix network synchronous)
-- TODO Remove smyvalka (& Updater.Repair)
-- TODO BlastThreadId(origin).
-- TODO cliblast, убрать тормоза
-- TODO АВТОМАТИЧЕСКОЕ ПЕРЕПОДКЛЮЧЕНИЕ
--      Останавливать вайп после нескольких безуспешных переподключений.
-- TODO считать баны, включать в ачивки
-- TODO Писать забаненные/сдохнувшие прокси в файл+(борда & причина/ексепшн)
-- TODO фильтровать забаненные / сдохнувшие.

--Antigate:
-- TODO: Configurable max_bid, sleepwait and sleepcaptcha
-- TODO отображать состояние антигейта в updWipeMessage (add hook)
--      например количество капч решаемых в данный момент или stat.php

--Updater:
-- TODO Кэширование манифеста (записывать ETag например)

-- == FUTURE IMPROVEMENTS ==
-- TODO Support 2chru.net
-- TODO better exceptions for 404, 403, strange 303 wakabapl(TooFastPost?), cloudflare ban, detect cloudflare when posting, mochan down.
-- TODO Пикчи со смитанусом на тему ссания в жопу из Kuso Miso Technique.
-- TODO add zip file permissions to zip-archive
-- TODO make updater a standalone library and release on hackage?
--      ("crude-autoupdater.cabal", it'll need quite a generalization to fit as
--      a general purpose library.)
-- TODO i18n (represent messages by types + typeclass?)
-- TODO config last thread time
-- TODO Показывать несколько капч одновременно

-- == REFACTORING ==
-- TODO Switch to immutable state, don't modify environment from widgets, send events instead.
-- TODO Being functional means modeling a program in a data-oriented fashon, not
--      effect-oriented. Right now it's as imperative as it gets.
-- TODO Replace (OriginStamp, Message) with appropriate type,
--      replace Message(SendCaptcha) with dedicated type, add a type for CompactStamp
-- TODO More type safety.(Any type safety?)
-- TODO More modularity.(Any modularity?)
-- TODO Move ssach/recaptcha/cloudflare-specific functionality to their own modules
-- FIXME Escaping.hs: Кажется за каждый reverse мне светит по ебалу
-- TODO cleanup
-- TODO document

instance Default Conf where
    def = Conf
        {coActiveBoards = []
        ,coPastaSet = FromThread
        ,coCreateThreads = True
        ,coImageFolder = "images"
        ,coAttachImages = True
        ,coAnnoy = True
        ,coHideOnSubmit = False
        ,coAnnoyErrors = True
#ifdef TEST
        ,coTray = False
#else
        ,coTray = True
#endif
        ,coWatermark = False
        ,coFirstLaunch = True
        ,coUseHttpProxy = False
        ,coHttpProxyFile = ""
        ,coUseSocksProxy = False
        ,coSocksProxyFile = ""
        ,coUseNoProxy = True
        ,coCaptchaMode = Gui
        ,coAntigateKey = []
        ,coAntigateHost = "antigate.com"
        ,coLastVersion = GtkBlastVersion version
        ,coPastaFile = bundledFile "pasta/shizik"
        ,coEscapeInv = False
        ,coEscapeWrd = False
        ,coSortingByAlphabet = True
        ,coShuffleReposts = False
        ,coRandomQuote = False
        ,coUsePostTimeout = False
        ,coPostTimeout = ssachPostTimeout SsachB
        ,coUseThreadTimeout = False
        ,coThreadTimeout = ssachThreadTimeout SsachB
        ,coUseFluctuation = False
        ,coFluctuation = 10
        ,coSage = True
        ,coMaxLines = 300
        ,coPastaText =
            "Хуй выгрызи уёбище выпроваживает он нас\n\n\n\n"
         ++ "Гагага, шизик, да ты же смешной ПИДОР\n\n\n\n"
         ++ "ШИЗИК, ТЫ СОВСЕМ ЕБАНУЛСЯ?\n\n\n\n"
        ,coVideoSet = VideoNothing
        ,coVideoFile = bundledFile "video/shizik"
        ,coVideoText =
            "http://www.youtube.com/watch?v=NkxVk-egpxs\n"
         ++ "http://www.youtube.com/watch?v=_B8bSmsPzhw\n"
         ++ "http://www.youtube.com/watch?v=O6PwHyBnSnY\n"
         ++ "http://www.youtube.com/watch?v=r05TYkdsKho"
        ,coPresolveCaptcha = False
        ,coBoardSpeedData = []
        }

helpMessage :: String
helpMessage =
    "Засиралка-вайпалка сосача, с гуи и автообновлением.\n"
 ++ "Справочный материал разбросан по тултипам, наводите мышку на интересующие "
 ++ "вас элементы. Если вам нужна помощь обращайтесь в соответствующий тред на "
 ++ "вашей борде, или в треды указанные на странице репозитория.\n"
 ++ "https://github.com/exbb2/BlastItWithPiss\n"
 ++ "Version: " ++ showVersion version

main :: IO ()
main = withSocketsDo $ do
    setNumCapabilities =<< getNumCapabilities

    args <- getArgs
    when (any (`elem` args) ["--help", "-h", "-?"]) $ do
       putStrLn $ fromString helpMessage
       exitSuccess
    when (any (`elem` args) ["-V", "--version"]) $ do
       putStrLn $ fromString $ showVersion version
       exitSuccess

     -- change workdir
#ifdef BINDIST
    (path, _) <- splitExecutablePath
    setCurrentDirectory path
#endif
    -- read configuration

    _t <- show <$> getZonedTime
    putInvisibleLog $
        "Starting gtkblast. Version "
        ++ fromString (showVersion version) ++ ". Current time is " ++ _t

    configfile <- (</> "config.json") <$> configDir
    conf <- readConfig configfile
    putInvisibleLog $ "Loaded config: " ++ show conf

    -- start

    handle (\(e::SomeException) -> do
      t <- getZonedTime
      putInvisibleLog $
        "Uncaught exception terminated program. Current time is "
        ++ show t ++ "\nException was: " ++ show e
      exitFailure) $ do

        -- init

        void $ initGUI
        builder <- builderNew
        builderAddFromFile builder $ bundledFile "resources/blast.glade"

        (env, setConf) <- createWidgetsAndFillEnv builder conf

        -- start main loop

        setMainLoop env configfile setConf

        -- start main gui

        i am playing the game
        the one that'll take me to my end
        i am waiting for the rain
        to wash up who i am

        libera me from $osach:
            DO THE IMPOSSIBLE!
            SEE THE INVISIBLE!
            ROW! ROW!
            FIGHT THE POWER!

            TOUCH THE UNTOUCHABLE!
            BREAK THE UNBREAKABLE!
            ROW! ROW!
            FIGHT THE POWER!

            ROW! ROW!
            FIGHT THE POWER!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [you lost The Game]

        -- say good bye

        putInvisibleLog =<<
          ("Finished wipe session, current time is " ++) . show <$> getZonedTime
